// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txilwgpfxgjklptrwjjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4aWx3Z3BmeGdqa2xwdHJ3ampkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzU2NjEsImV4cCI6MjA2NDU1MTY2MX0.NpXnxyXsE_nzLjpZHgbEq7KG9yOmzdkXh1lTXiS1VhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);